### PR TITLE
Upgrade for 1-10

### PR DESCRIPTION
**Pull request by willtebbutt**
I think this actually handles both 1.9 and 1.10. We'll know when CI passes.

### CODE REVIEW

**Comment by willtebbutt** [comment]
@dfdx looks like it works.

**Comment by willtebbutt** [comment]
Additionally, do we need to be testing on nightly, or shall we just test on 1.9 and 1 (which will correspond to 1.10 in the relatively near future I assume)?

**Comment by dfdx** [comment]
Julia 1.6 is still the official LTS version, and it's what we have in `Project.toml`. So the default plan was to support it until the next LTS version. Do you find issues that cannot be handled (easily) on Julia < 1.9?

Regarding nightlies, I think it constantly fails for over a year now and we don't really adapt the package for pre-release versions. So yes, I think we can drop it and test only on the released versions.

**Comment by willtebbutt** [comment]
> Julia 1.6 is still the official LTS version, and it's what we have in Project.toml. So the default plan was to support it until the next LTS version. Do you find issues that cannot be handled (easily) on Julia < 1.9?

Ah, okay. I got the impression from https://github.com/dfdx/Umlaut.jl/pull/43 that you were happy to drop support for 1.6 if we tag a new minor version. The reason being that we don't need CompilerPluginTools from 1.9 onwards, and CompilerPluginTools does not even precompile on 1.10, meaning that Umlaut cannot precompile on 1.10. Have I misunderstood your position?

> Regarding nightlies, I think it constantly fails for over a year now and we don't really adapt the package for pre-release versions. So yes, I think we can drop it and test only on the released versions.

Sounds good.

**Comment by dfdx** [comment]
All true, I forgot we discussed version 1.10 specifically, now the puzzle has come together. 

The general principle I follow is to support old versions as long as they don't block the progress. For Julia 1.10-beta2 the situation was unclear because pre-release versions often change - why to make life harder for the dependent packages if it may be fixed soon! With the current version 1.10-rc1 it's unlikely that `CompilerPluginTools will start working`, so dropping the old versions of Julia sounds justified. 

I will merge the PR, update compat and tag a new version.

**Pull request merged**
